java.lang.ClassNotFoundException: com.nimingban.cordova.savetophotoalbum  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nimingban.cordova.savetophotoalbum" on path: DexPathList[[zip file "/data/app/io.cordova.hellocordova-1/base.apk"]